### ISSUE TITLE
blockquotes issues 

### ISSUE THREAD

**Issue by juanfrax** [logseq/awesome-logseq#35]
Hi,

I'm testing your software and I had noticed that when I try to add some blockquotes with other elements  logseq does not works properly I tested the same code in other markdown app and it does work.

```
>##### the quarterly results look great!
>
>- Revenue was off the chart
>- Profits were higher than ever.
>*Everything* is going *Well*

```
Outcome

![Screen Shot 2021-12-29 at 1 04 22 PM](https://user-images.githubusercontent.com/17235389/147691289-79f22e0c-9c58-4b1c-a420-6be90277b053.png)

**Comment by Bad3r** [comment]
Please open a bug report in the official repo [https://github.com/logseq/logseq/issues](https://github.com/logseq/logseq/issues) 

This repo is only used to host the awesome list.

**Comment by cnrpman** [comment]
Closing this as it's already moved to the LogSeq repo
