### ISSUE TITLE
Add Simple Dark Theme

### ISSUE THREAD

**Issue by flowerornament** [logseq/awesome-logseq#37]
I published a simple dark theme here based on logseq-bonofix-theme. It's not up to the quality level of other themes here, but I thought I'd mention it in case you want to include it:

https://github.com/flowerornament/logseq-simple-dark-theme/

<img width="1420" alt="Screen Shot 2022-01-21 at 5 23 20 PM" src="https://user-images.githubusercontent.com/31774/150619410-c74e3b28-97c4-4362-afb0-44a3a53b8ea4.png">

**Comment by cnrpman** [comment]
Pretty cool!
Can you open a PR to add the line?
